### ISSUE TITLE
Resulting dataframe filled with <NA>

### ISSUE THREAD

**Issue by Brandomycete** [brendanf/FUNGuildR#7]
Hi,

Thank you for creating this package, I think it will be very useful! I am trying use it now but I am having an issue where the resulting table is filled with <NA> e.g.:
Taxonomy taxon guid mbNumber taxonomicLevel trophicMode guild confidenceRanking growthForm trait notes citationSource
1              Acanthobasidium delicatum  <NA> <NA>     <NA>           <NA>        <NA>  <NA>              <NA>       <NA>  <NA>  <NA>           <NA>
2                            Acephala NA  <NA> <NA>     <NA>           <NA>        <NA>  <NA>              <NA>       <NA>  <NA>  <NA>           <NA>

I tried manually downloading the database to see if that helped but no luck, this is the code I ran:
guilds <- funguild_assign(taxonomy, db = fung)

Still ran into the same issue. As a sanity check I did make sure that my species are in the database and after checking a few they definitely are.

The only error message I have had is the following during package install:
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Brandon\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\Brandon\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Brandon\AppData\Local\R\win-library\4.3\00LOCK\fansi\libs\x64\fansi.dll to C:\Users\Brandon\AppData\Local\R\win-library\4.3\fansi\libs\x64\fansi.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Brandon\AppData\Local\R\win-library\4.3\00LOCK\purrr\libs\x64\purrr.dll to C:\Users\Brandon\AppData\Local\R\win-library\4.3\purrr\libs\x64\purrr.dll: Permission denied
4: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Brandon\AppData\Local\R\win-library\4.3\00LOCK\dplyr\libs\x64\dplyr.dll to C:\Users\Brandon\AppData\Local\R\win-library\4.3\dplyr\libs\x64\dplyr.dll: Permission denied
5: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Brandon\AppData\Local\R\win-library\4.3\00LOCK\jsonlite\libs\x64\jsonlite.dll to C:\Users\Brandon\AppData\Local\R\win-library\4.3\jsonlite\libs\x64\jsonlite.dll: Permission denied
6: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\Brandon\AppData\Local\R\win-library\4.3\00LOCK\curl\libs\x64\curl.dll to C:\Users\Brandon\AppData\Local\R\win-library\4.3\curl\libs\x64\curl.dll: Permission denied

Thank you for any help!

**Comment by Brandomycete** [comment]
![NA issue](https://github.com/brendanf/FUNGuildR/assets/148214994/136b844e-2cb2-4105-af21-07fe0c8541c0)

Hi, sorry I realise the NAs dissapeared from my question, have uploaded an image of the problem

**Comment by brendanf** [comment]
Hi @Brandomycete,

The Taxonomy column is intended to include not just the species name, but the full taxonomy, e.g. something like `Fungi;Basidiomycota;Agaricomycetes;Russulales;Stereaceae;Acanthobasidium;Acanthobasidium delicatum`.

Investigating your case has actually led me to realize that the first level of the taxonomy is not actually used in matching.  In the typical case where the first taxon is "Fungi", that is not important because we don't have guilds assigned to "Fungi".  In your case however, it ends up being the genus name, and you cannot get any results without that. 

I will fix this, because in many cases genus and species should be able to give a result; in the mean time you can get results by prepending the rest of the taxonomy, or at least the family name, before your binomials. Going further back than that may give you a few more results in cases where FUNGuild has listings for the family but not the genus or species. My example used semicolons to separate the ranks, but comma, underscore, and colon are also allowed.

**Comment by Brandomycete** [comment]
Thank you so much! I went back and icluded the entire taxonomy and everything has worked. :D
